version: '3'
services:
  app:
    build: ./src/golang
    ports:
      - '8080:8080'
    volumes:
      - './src/golang/src:/go/src/github.com/blacknikka/go-blog'
    tty: true
  db:
    build: ./src/db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
